#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
#bspc config window_gap          12

bspc config split_ratio          0.5
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Inkscape desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
